backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Json;

use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'request-password-reset', 'reset-password','about','webcam','mycam','contactus','termsandconditions','test'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'changepassword', 'login', 'terms', 'viewapplication', 'viewapplication2', 'change-password','contactus','termsandconditions'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    /*public function actionIndex()
    {
        return $this->render('index');
    }*/
    
    public function actionIndex() {

        $session = Yii::$app->session;

        if (!Yii::$app->user->isGuest) {

            //if (($session['currentPersona'] == "owner") || ($session['currentPersona'] == "tenant")) {
            if (($session['currentRole'] == Yii::$app->params['role.type.administrator'])) {
                return $this->render('dashboard_administrator');
            } else if (($session['currentRole'] == Yii::$app->params['role.type.management'])) {
                return $this->render('dashboard_management');
            } else if (($session['currentRole'] == Yii::$app->params['role.type.support'])) {
                return $this->render('dashboard_support');
            } else if (($session['currentRole'] == Yii::$app->params['role.type.painter'])) {
                return $this->render('dashboard_painter');
            }
        } else {
            return $this->redirect(['home']);
        }
        //return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $this->layout = 'loginlayout';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            Yii::$app->ici->addtolog('success', Yii::$app->user->id);
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }
    
    public function actionContactus()
    {
        //echo 'test';
        return $this->render('contactus');
    }
    
    public function actionTermsandconditions()
    {
        //echo 'test';
        return $this->render('termsandconditions');
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('test');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    /*public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }*/

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $this->layout = 'loginlayout';
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        $this->layout = 'loginlayout';
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
    
    public function actionWebcam(){
        //echo 'test';
        $img = '<img src="/upload/documents/camera757.jpg" class="user-image" alt="User Image">';
        return $this->render('webcam', [
                //'model' => $model,
                'img' => $img,
            ]);
    }
    
    public function actionTest(){
        echo 'test live test 12334567';
        $message = "hishihan";
        $message = html_entity_decode($message, ENT_QUOTES, 'utf-8'); 
        $message = urlencode($message);
        //$destination = $myuser->cust_mobile;
        //$new = substr($myuser->mobile, 0, -3) . 'xxx';
        //echo $short.'<br>';
        $mobile = "60111889597";

                    
        $username = urlencode(Yii::$app->params['sms.username']);
        $password = urlencode(Yii::$app->params['sms.password']);
        $sender_id = urlencode("66300");
        $type = '1';
        
        $link = "https://www.isms.com.my/isms_send_all.php";
        $link .= "?un=$username&pwd=$password&dstno=$mobile&msg=$message&type=$type&sendid=$sender_id";
        
 
        //$result = Yii::$app->residenz->ismscURL($fp);
        $http = curl_init($link);
        curl_setopt($http, CURLOPT_RETURNTRANSFER, TRUE);
        $http_result = curl_exec($http);
        $http_status = curl_getinfo($http, CURLINFO_HTTP_CODE);
        curl_close($http);

        return $http_result;
        die();
    }
    public function actionMycam(){
        //echo 'test';
        $encoded_data = $_POST['username'];        
        $image_data = base64_decode( $encoded_data );
        $path = Yii::getAlias('@frontend') .'/web/upload/documents/';
        $file_name = $path;
        $image_name = substr(uniqid(rand(1,6)), 0, 8).'.jpg';
        $file = $file_name . $image_name;

        $success = file_put_contents($file, $image_data);
        
        if ($success) {
            //echo "Successfully uploaded"; 
            $response['image_name'] = $image_name;
        } else {
            //echo "Not uploaded";
            $response = null;
        }
        echo json_encode($response);
    }
    
    
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/contactus.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact Us';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="col-md-6">
    <div class="box box-default">
        <div class="box-header with-border">
            <i class="fa fa-life-ring"></i>
            <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <h4>For further enquiries, please contact us at :</h4>
            <p><label>Call us :</label> 1-800-88-9338 (Mon – Fri, 9am-5pm)</p>
            <p><label>Email us :</label> customercare.my@akzonobel.com</p>

        </div><!-- /.box-body -->
    </div><!-- /.box -->
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/termsandconditions.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Terms and Conditions';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="col-md-12">
    <div class="box box-default">
        <div class="box-header with-border">
            <i class="fa fa-handshake-o"></i>
            <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
        </div><!-- /.box-header -->
        <div class="box-body">
            <h3>Terms and Conditions of Dulux Painter's Club Loyalty Program "Loyalty Program"</h3>
            <br>
            <ol>
                <li>To enter the Loyalty Program, you must complete fully the Dulux Painter’s Club Application form and submit the form back to Akzo Nobel Paints (Malaysia) Sdn Bhd through Akzo Nobel Paints (Malaysia) Sdn Bhd authorised representatives or by depositing forms at participating dealers.</li>
                <li>By submitting the completed Dulux Painter’s Club Application form, you agree to comply with these terms & conditions.</li>
                <li>Entry is open only to Malaysian citizens aged 18 and over, who conduct painting as part of their business, at the date of registration. Employees of Akzo Nobel Paints (Malaysia) Sdn Bhd are ineligible to participate in the Loyalty Program, as are members of their families or households or any other person connected with the running of the Loyalty Program. No third party or joint submissions will be accepted.
</li><li>Akzo Nobel Paints (Malaysia) Sdn Bhd will verify each application form and reserves the right, with or without cause, to exclude any Participants in this Loyalty Program where there has been a violation of any of these terms & conditions.
</li><li>Upon approval of application for membership into the Dulux Painter’s Club Loyalty Program, a membership pack shall be sent to each member. The membership pack will contain a membership card that will uniquely identify the member and will be used by the member to participate in any offer or event.
</li><li>Loyalty Program members must notify Akzo Nobel Paints (Malaysia) Sdn Bhd promptly if there is a change in their particulars.</li>
<h4 class="text-bold">Dulux Painter’s Club Loyalty Program Mechanics</h4>
<li>Dulux Painter's Club Loyalty Program membership card is applicable in Malaysia only.
</li><li>Dulux Painter's Club Loyalty Program membership card is not transferable, refundable or exchangeable for cash.
</li><li>To qualify for points awarding and points redemption as specified in the Dulux Painter's Club Loyalty Program, Participants must submit 1 copy of each Tax Invoice along with written Membership ID as proof of purchase to Akzo Nobel Paints (Malaysia) Sdn Bhd authorized representatives.
</li><li>Akzo Nobel Paints (Malaysia) Sdn Bhd assumes no responsibility for lost, unauthorised, misdirected, illegible, falsified, delayed or incomplete proof of purchases, all of which are invalid or void, or for difficulties experienced in submitting a proof of purchase, including as a result of any technical delay, failure or defect.
</li><li>Akzo Nobel Paints (Malaysia) Sdn Bhd reserves the right to vary the offers and the terms of the membership without prior notice.
</li><li>Akzo Nobel Paints (Malaysia) Sdn Bhd decision on all matters relating to Dulux Painter's Club Loyalty Program is final and no correspondence will be entertained</li>
<h4 class="text-bold">General</h4>
            <li>To the fullest extent permitted by law, the Promoter excludes: 
                <ul>
                    <li>all conditions, warranties and other terms which might otherwise be implied; and</li>
                    <li>any liability for any direct, indirect or consequential loss or damage incurred by any Participant in connection with this Loyalty Program.  This shall not be deemed to exclude or restrict liability for death or personal injury resulting from the negligence of Akzo Nobel Paints (Malaysia) Sdn Bhd, or its employees or agents.</li>
                </ul>
            </li>
            <li>Akzo Nobel Paints (Malaysia) Sdn Bhd is committed to protecting the privacy of Participants.  By participating in this Loyalty Program, Participants acknowledge and agree that certain personal data relating to them (including their name and geographical location) may be disclosed to third parties. Any information collected in connection with this Competition will only be used by the Akzo Nobel Paints (Malaysia) Sdn Bhd or their agents for the purposes of marketing or administering this Loyalty Program and future promotions or publicity material relating to this Loyalty Program.</li>
            <li>Akzo Nobel Paints (Malaysia) Sdn Bhd reserves the right to withdraw, delay or amend this Loyalty Program in whole or in part,  without prior notice or compensation, and will not be in breach of these terms or liable for any delay or failure in performing its obligations due to such circumstances
</li><li>If any court or competent authority finds that any provision of these terms and conditions (or part of any provision) is invalid, illegal or unenforceable, that provision or part-provision shall, to the extent required, be deemed to be deleted, and the validity and enforceability of the other provisions of these terms and conditions shall not be affected.
</li><li>These terms and conditions are governed by the laws of Malaysia and are subject to the exclusive jurisdiction of the Malaysia courts. 
</li><li>For all queries or issues with this competition, please contact: customercare.my@akzonobel.com or call 1800 88 9338 (Mon-Fri, 9am-5pm)
</li>
            </ol>


        </div><!-- /.box-body -->
    </div><!-- /.box -->
</div>

frontend/views/site/test.php
<?php
echo 'test';
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

frontend/views/site/webcam.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Webcam';
$this->params['breadcrumbs'][] = $this->title;
?>
	

<script type="text/javascript" src="/themes/adminlte/webcamjs/webcam.js"></script>

                
<div class="bs-example">
    <!-- Button HTML (to Trigger Modal) -->
    <a href="#myModal" class="btn btn-lg btn-primary" data-toggle="modal">Launch Demo Modal</a>
    
    <!-- Modal HTML -->
    
</div>  


	
	<h1>WebcamJS Test Page</h1>
	<h3>Demonstrates all features at once</h3>
        <input id="mydata" type="text" name="mydata" value=""/>
	<div style="margin-top:5px; margin-bottom:20px;">Captures large 480x480 cropped image while displaying live 240x240 preview, flipped horizontally (mirrored), and allows preview before save.</div>
	<div id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <input id="mydata" type="text" name="mydata" value=""/>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Confirmation</h4>
                </div>
                <div class="modal-body">
                    <div id="my_camera"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onClick="save_photo()">Save changes</button>
                </div>
            </div>
        </div>
    </div>
	<div id="my_photo_booth">
		<div id="my_camera1"></div>
		
		
		<!-- First, include the Webcam.js JavaScript Library -->

		
		<!-- Configure a few settings and attach camera -->
		<script language="JavaScript">
			Webcam.set({
				// live preview size
				width: 700,
				height: 420,
				
				// device capture size
				dest_width: 640,
				dest_height: 480,
				
				// final cropped size
				crop_width: 480,
				crop_height: 480,
				
				// format and quality
				image_format: 'jpeg',
				jpeg_quality: 90,
				
				// flip horizontal (mirror mode)
				flip_horiz: true
			});
			
			$('#myModal').on('show.bs.modal', function () {				
			  Webcam.attach( '#my_camera' );
			})
			
			$("#myModal").on("hidden.bs.modal", function () {
				Webcam.reset();
			});
		</script>
		
		<!-- A button for taking snaps -->

	</div>
	
	<div id="results" style="display:none">
		<!-- Your captured image will appear here... -->
	</div>
	
	<!-- Code to handle taking the snapshot and displaying it locally -->
	<script language="JavaScript">
		// preload shutter audio clip
		var shutter = new Audio();
		shutter.autoplay = false;
		shutter.src = navigator.userAgent.match(/Firefox/) ? 'shutter.ogg' : 'shutter.mp3';
		

		
		function save_photo() {
			// actually snap photo (from preview freeze) and display it
			Webcam.snap( function(data_uri) {
				//try { shutter.currentTime = 0; } catch(e) {;} // fails in IE
			//shutter.play();
                        

                            var raw_image_data = data_uri.replace(/^data\:image\/\w+\;base64\,/, '');
                            document.getElementById('mydata').value = raw_image_data;
                            
                            var username = raw_image_data;
                                
                                $.ajax({
                                    url: '<?php echo \Yii::$app->getUrlManager()->createUrl('/site/mycam') ?>',
                                    type: 'POST',
                                     data: { username: username },
                                     success: function(data) {
                                         alert(data);

                                     }
                                 });


			// freeze camera so user can preview current frame
			Webcam.freeze();
				document.getElementById('results').innerHTML = 
					'<h2>Here is your large, cropped image:</h2>' + 
					'<img src="'+data_uri+'"/><br/></br>' + 
					'<a href="'+data_uri+'" target="_blank">Open image in new window...</a>';
				
				// shut down camera, stop capturing
				//Webcam.reset();
				
				// show results, hide photo booth
				document.getElementById('results').style.display = '';
				document.getElementById('my_photo_booth').style.display = 'none';
				
			} );
			$('#myModal').modal('toggle');
				Webcam.reset();
		}
	</script>